//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class YapilacaklarListesi
    {
        public int ListeId { get; set; }
        public string KullaniciAd { get; set; }
        public Nullable<System.DateTime> YapilacaklarTarih { get; set; }
        public Nullable<System.TimeSpan> YapilacaklarSaat { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
    }
}
